### ISSUE TITLE
Embedding data generation

### ISSUE THREAD

**Issue by ypenglyn** [xuanyuan14/CACM-master#4]
Hi, I have a question regarding the data generation for node2vec. I got data from TianGong-ST page [here](http://www.thuir.cn/tiangong-st/) by contacting frankyzf94@gmail.com. But the following command seems not working well due to missing `vtype` for each document interaction.

```
python TianGong-ST-CACM.py --xml_clean --dict_list --txt --node2vec --human_label_txt_for_CACM --dataset sogousessiontrack2018.xml --input ../ST/data/ --output ./data
===> cleaning xml file...
  - start reading from xml file...
  - read 50265215 lines
  - start removing useless lines...
  - remove 1000000 lines...
  - remove 2000000 lines...
  - remove 3000000 lines...
  - remove 4000000 lines...
  - remove 5000000 lines...
  - remove 6000000 lines...
  - remove 7000000 lines...
  - remove 8000000 lines...
  - remove 9000000 lines...
  - remove 10000000 lines...
  - remove 11000000 lines...
  - remove 12000000 lines...
  - remove 13000000 lines...
  - remove 14000000 lines...
  - remove 15000000 lines...
  - remove 16000000 lines...
  - remove 17000000 lines...
  - remove 18000000 lines...
  - remove 19000000 lines...
  - remove 20000000 lines...
  - remove 21000000 lines...
  - remove 22000000 lines...
  - remove 23000000 lines...
  - remove 24000000 lines...
  - remove 25000000 lines...
  - remove 26000000 lines...
  - remove 27000000 lines...
  - remove 28000000 lines...
  - remove 29000000 lines...
  - remove 30000000 lines...
  - remove 31000000 lines...
  - remove 32000000 lines...
  - remove 33000000 lines...
  - remove 34000000 lines...
  - remove 35000000 lines...
  - read 50265215 lines
  - totally 356252 iteractions
  - totally remove 35981452 lines
===> generating dicts and lists...
  - start parsing xml file...
  - generating infos_per_session...
Traceback (most recent call last):
  File "TianGong-ST-CACM.py", line 526, in <module>
    main()
  File "TianGong-ST-CACM.py", line 510, in main
    generate_dict_list(args)
  File "TianGong-ST-CACM.py", line 121, in generate_dict_list
    vtype = doc.getElementsByTagName('vtype')[0].childNodes[0].data
IndexError: list index out of range
```
I'm new to this dataset and not sure where to find the cause for this. Would you please give more information about what is `vtype` and what might be the possible cause for this? Thanks a lot!

**Comment by xuanyuan14** [comment]
You should update the Tiangong-ST data. The first version of our data did not contain the vertical information, but we have updated the dataset several months ago. You can contact that E-mail again to obtain the updated dataset (which is named as "sogousessiontrack2018_updated_20200513.xml").

**Comment by ypenglyn** [comment]
Thanks for the quick response!
